### ISSUE TITLE
rnbw.company enhancements

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw.company#3]
- [x]  add `gap-column` and gap-row to everywhere there’s a side by side paragraphs blocks so that text blocks won’t have too much vertical space in mobile. both on site and guide.
- [x]  make the code view in `<rnbw-preview> `always appear on the right side. in mobile sizes significantly.
- [x]  make the dropdown in `<rnbw-editor>` independently wide to fit in mobile sizes.
- [x]  stretch the items in the command menus to take the whole mobile width for the sections where it now appears. also at the guide
- [x]  optimize the` <rnbw-blog>` for mobile. make height higher or dynamic for mobile view.
- [x]  at https://guide.rnbw.dev/quick-start#code - align the code in mobile.

**Comment by atulbhatt-system32** [comment]
@edenvidal 
`for some reason, the borders in “more imagine, less crafting” aren’t getting the`

Seems like the above point is not complete.
